# Generated by Django 5.2.3 on 2026-02-02 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("arches_lingo", "0002_load_lingo_lists"),
    ]

    LANGUAGES = [
        {"code": "ar", "name": "Arabic", "default_direction": "rtl"},
        {"code": "de", "name": "German"},
        {"code": "el", "name": "Greek"},
        {"code": "es", "name": "Spanish"},
        {"code": "fr", "name": "French"},
        {"code": "pt", "name": "Portuguese"},
        {"code": "zh", "name": "Chinese"},
    ]

    def forward(apps, schema_editor):
        Language = apps.get_model("models", "Language")
        existing_languages = Language.objects.values_list("code", flat=True)
        new_languages = []
        for lang in Migration.LANGUAGES:
            if lang["code"] not in existing_languages:
                new_languages.append(
                    Language(
                        code=lang["code"],
                        name=lang["name"],
                        default_direction=lang.get("default_direction", "ltr"),
                    )
                )
        Language.objects.bulk_create(new_languages)

    operations = [
        migrations.RunPython(forward),
    ]
