# Generated by Django 5.2.3 on 2026-02-02 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("arches_lingo", "0002_load_lingo_lists"),
    ]

    LANGUAGES = [
        {"code": "ar", "name": "Arabic", "default_direction": "rtl"},
        {"code": "de", "name": "German"},
        {"code": "el", "name": "Greek"},
        {"code": "es", "name": "Spanish"},
        {"code": "fr", "name": "French"},
        {"code": "pt", "name": "Portuguese"},
        {"code": "zh", "name": "Chinese"},
    ]

    def forward(apps, schema_editor):
        Language = apps.get_model("models", "Language")
        existing_language_codes = set(Language.objects.values_list("code", flat=True))
        new_languages = []
        for language_definition in Migration.LANGUAGES:
            if language_definition["code"] not in existing_language_codes:
                new_languages.append(
                    Language(
                        code=language_definition["code"],
                        name=language_definition["name"],
                        default_direction=language_definition.get(
                            "default_direction", "ltr"
                        ),
                    )
                )
        Language.objects.bulk_create(new_languages)

    def reverse(apps, schema_editor):
        Language = apps.get_model("models", "Language")
        language_codes = [
            language_definition["code"] for language_definition in Migration.LANGUAGES
        ]
        Language.objects.filter(code__in=language_codes).delete()

    operations = [
        migrations.RunPython(forward, reverse),
    ]
