# Generated by Django 5.2.3 on 2026-01-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("arches_lingo", "0002_load_lingo_lists"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConceptIdentifierCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheme_resource_instance_id", models.UUIDField(unique=True)),
                ("start_number", models.BigIntegerField(default=1)),
                ("next_number", models.BigIntegerField(default=1)),
            ],
            options={
                "db_table": "concept_identifier_counters",
            },
        ),
    ]
