# Generated by Django 5.2.3 on 2026-01-21 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("arches_lingo", "0002_load_lingo_lists"),
        ("models", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConceptIdentifierCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scheme",
                    models.OneToOneField(
                        db_column="scheme_resource_instance_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="concept_identifier_counter",
                        to="models.resourceinstance",
                    ),
                ),
                ("start_number", models.BigIntegerField(default=1)),
                ("next_number", models.BigIntegerField(default=1)),
            ],
            options={
                "db_table": "concept_identifier_counters",
            },
        ),
    ]
