# Generated by Django 5.2.3 on 2026-01-27 14:08


import arches_lingo.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arches_lingo", "0005_add_scheme_lifecycle_handler_concept_identifier"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchemeURITemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url_template",
                    models.TextField(
                        default=arches_lingo.models.default_scheme_uri_template_value
                    ),
                ),
                (
                    "scheme",
                    models.OneToOneField(
                        db_column="scheme_resource_instance_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheme_uri_template",
                        to="models.resourceinstance",
                    ),
                ),
            ],
            options={
                "db_table": "scheme_uri_templates",
            },
        ),
    ]
