# Generated by Django 5.2.16 on 2026-09-18 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arches_lingo", "0018_add_related_image_gin_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConceptMerge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("survivor_concept_id", models.UUIDField(db_index=True)),
                ("absorbed_concept_id", models.UUIDField(db_index=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "edit_transaction_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "selections",
                    models.JSONField(
                        default=dict,
                        help_text="The merge request payload: chosen tiles and merge options.",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lingo_concept_merges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "concept merge",
                "verbose_name_plural": "concept merges",
                "ordering": ["-created"],
            },
        ),
    ]
