# Generated by Django 5.2.16 on 2026-09-21 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arches_lingo", "0019_add_concept_merge"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConceptMatchRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("finished", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("complete", "Complete"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        default=dict,
                        help_text="Scope, signals and thresholds this run was started with.",
                    ),
                ),
                ("candidate_count", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lingo_concept_match_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "concept match run",
                "verbose_name_plural": "concept match runs",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="ConceptMatchCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("concept_a_id", models.UUIDField(db_index=True)),
                ("concept_b_id", models.UUIDField(db_index=True)),
                (
                    "score",
                    models.FloatField(
                        help_text="1.0 for an exact signal, the similarity for a fuzzy one."
                    ),
                ),
                (
                    "signal",
                    models.CharField(
                        choices=[
                            ("shared_identifier", "Shared identifier"),
                            ("exact_label", "Exact label"),
                            ("trigram", "Similar label"),
                        ],
                        max_length=32,
                    ),
                ),
                ("evidence", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("dismissed", "Dismissed"),
                            ("linked", "Linked"),
                            ("merged", "Merged"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lingo_reviewed_match_candidates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidates",
                        to="arches_lingo.conceptmatchrun",
                    ),
                ),
            ],
            options={
                "verbose_name": "concept match candidate",
                "verbose_name_plural": "concept match candidates",
                "ordering": ["-score", "pk"],
                "indexes": [
                    models.Index(
                        fields=["run", "status", "-score"],
                        name="lingo_candidate_queue_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("run", "concept_a_id", "concept_b_id"),
                        name="unique_candidate_pair_per_run",
                    )
                ],
            },
        ),
    ]
