# Generated by Django 5.2.16 on 2026-09-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arches_lingo", "0020_add_concept_match_detection"),
    ]

    operations = [
        migrations.AddField(
            model_name="conceptmatchrun",
            name="last_progress",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
