# Generated by Django 5.2.16 on 2026-09-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arches_lingo", "0021_conceptmatchrun_last_progress"),
    ]

    operations = [
        migrations.AddField(
            model_name="conceptmatchrun",
            name="name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
